export const handleRestart = ({
  playerMaxHealth,
  setPlayerMaxHealth,
  setPlayerHealth,
  setPlayerDamage,
  setPlayerLevel,
  currentMonster,
  setCurrentMonster,
  setMonsterHealth,
  setMonsterDamage,
  setShowDamage,
  setCombatLog,
  setGameMessage,
  setIsFirstRound,
  setHeroClass,
  setShowSelection,
  setIsButtonDisabled,
  setDefeatedMonsters,
  monsters,
  setWasAttackButtonPressed,
}) => {
  setPlayerMaxHealth(200);
  setPlayerHealth(playerMaxHealth);
  setPlayerDamage(0);
  setPlayerLevel(1);
  setCurrentMonster(monsters[0]);
  setMonsterHealth(monsters[0].health);
  setMonsterDamage(0);
  setShowDamage(false);
  setCombatLog([]);
  setGameMessage(
    `A wild ${currentMonster.name} appeared in front of you! \nGet your weapons ready!`
  );
  setIsFirstRound(true);
  setHeroClass("");
  setShowSelection(false);
  setIsButtonDisabled(false);
  setDefeatedMonsters(0);
  setWasAttackButtonPressed(false);
};
